### ISSUE TITLE
Backlog's window height changes after every load

### ISSUE THREAD

**Issue by lewri** [czytelny/backlog#26] opened 2017-11-21 12:46 UTC
Hopefully this one is easier to work out than the previous issue.
I noticed every time I re-open Backlog, its Window height increases. This seems to continue happening to the point where the window goes off screen.

I imagine I would expect to find a setting that preserved the application's window height for the next load.

Lewri

**Comment by czytelny** [comment] 2017-11-25 19:38
Actually this feature is supported by default (although seems that in some cases not working as expected...) What is persisted is: window placement & height + width. Does windows placement work for you ? (eg. move Backlog window to right corner of your screen, close app and open it again - it should appear exactly in the same place). Maybe you have some kind of interface zooming option set on in system ?

**Comment by czytelny** [comment] 2018-03-13 20:36
@lewri this should be fixed in v1.6.0 can you please check it out ?

**Comment by lewri** [comment] 2018-04-25 01:11
Hi sorry for a long delay. This is fixed now.

**Comment by czytelny** [comment] 2018-07-04 19:20
@lewri another electron version bump, maybe now it works ? :) v1.7.0. I can't reproduce it although I'm using backlog almost every day

**Comment by czytelny** [comment] 2018-07-28 12:37
closing due to inactivity and fact I can't reproduce it. If you are experiencing such issue, please share some details and I'll reopen

**Closed by czytelny** 2018-07-28 12:37 UTC
Labels: bug
