### ISSUE TITLE
settings bug?

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#12] opened 2017-10-05 17:20 UTC
sometimes when I click on settings nothing really happens. 
doesn't really open them at all.

**Comment by czytelny** [comment] 2017-10-08 16:19
Which OS ? any more details ? anything specific ? it's hard to say what can cause this, because I never encountered such issue.. and if I can't reproduce it I won't be able to provide any fix

**Comment by diomed** [comment] 2017-10-08 16:31
it's on Windows 10.

I open it once, and every next time I can't open at all.
It's like it doesn't recognize me clicking on Settings.

**Comment by czytelny** [comment] 2017-10-28 14:59
I found the issue - when closing modal by clicking outside - it cause problem with re-opening. Will be fixed in v1.4.1 release

**Comment by czytelny** [comment] 2017-10-28 15:35
fixed in v1.4.1

**Closed by czytelny** 2017-10-28 15:35 UTC
